CREATE TABLE `icertportal` (
  `created_t` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` int(10) DEFAULT NULL,
  `caseNumber` varchar(20) NOT NULL,
  `jobPostingDate` date DEFAULT NULL,
  `caseType` varchar(20) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `employer` varchar(500) DEFAULT NULL,
  `startDate` date DEFAULT NULL,
  `endDate` date DEFAULT NULL,
  `jobTitle` varchar(200) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `done` varchar(5) DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`caseNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `icertdata` (
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id` int(10) NOT NULL,
  `employer` varchar(100) DEFAULT NULL,
  `empadd1` varchar(40) DEFAULT NULL,
  `empadd2` varchar(30) DEFAULT NULL,
  `empcity` varchar(40) DEFAULT NULL,
  `empstate` varchar(30) DEFAULT NULL,
  `empcountry` varchar(50) DEFAULT NULL,
  `empzipcode` varchar(15) DEFAULT NULL,
  `employerphone` varchar(15) DEFAULT NULL,
  `empnumemployees` int(6) DEFAULT NULL,
  `empyr` int(4) DEFAULT NULL,
  `emplastname` varchar(20) DEFAULT NULL,
  `empfirstname` varchar(20) DEFAULT NULL,
  `empphone` varchar(15) DEFAULT NULL,
  `empemail` varchar(40) DEFAULT NULL,
  `attorneylastname` varchar(20) DEFAULT NULL,
  `attorneyfirstname` varchar(20) DEFAULT NULL,
  `attorneyphone` varchar(20) DEFAULT NULL,
  `attorneyadd1` varchar(40) DEFAULT NULL,
  `attorneyadd2` varchar(100) DEFAULT NULL,
  `attorneycity` varchar(20) DEFAULT NULL,
  `attorneystate` varchar(20) DEFAULT NULL,
  `attorneycountry` varchar(50) DEFAULT NULL,
  `attorneyzip` varchar(20) DEFAULT NULL,
  `attorneyemail` varchar(50) DEFAULT NULL,
  `PWnum` varchar(20) NOT NULL,
  `occupation` varchar(100) DEFAULT NULL,
  `skilllevel` varchar(100) DEFAULT NULL,
  `prevailingwage` float(10,2) DEFAULT NULL,
  `pwsource` varchar(30) DEFAULT NULL,
  `determinationdate` date DEFAULT NULL,
  `expirationdate` date DEFAULT NULL,
  `OfferedWageFrom` float(10,2) DEFAULT NULL,
  `offeredwageto` float(10,2) DEFAULT NULL,
  `workadd1` varchar(100) DEFAULT NULL,
  `workadd2` varchar(100) DEFAULT NULL,
  `workcity` varchar(100) DEFAULT NULL,
  `workstate` varchar(100) DEFAULT NULL,
  `workzip` varchar(10) DEFAULT NULL,
  `jobtitle` varchar(100) DEFAULT NULL,
  `educationmin` varchar(100) DEFAULT NULL,
  `major` varchar(100) DEFAULT NULL,
  `trainingrequired` varchar(10) DEFAULT NULL,
  `alteducation` varchar(100) DEFAULT NULL,
  `numyrexperience` int(3) DEFAULT NULL,
  `jobduties` text,
  `specificskill` text,
  `SWAstartdate` date DEFAULT NULL,
  `SWAenddate` date DEFAULT NULL,
  `newspaper` varchar(100) DEFAULT NULL,
  `advdatefirst` date DEFAULT NULL,
  `advdatesecond` date DEFAULT NULL,
  `empwebsitepostdatefrom` date DEFAULT NULL,
  `empwebsitepostdateto` date DEFAULT NULL,
  `jobsearchwebsitefrom` date DEFAULT NULL,
  `jobsearchwebsiteto` date DEFAULT NULL,
  `localnewspaperdatefrom` date DEFAULT NULL,
  `localnewspaperdateto` date DEFAULT NULL,
  `aliencity` varchar(100) DEFAULT NULL,
  `alienstate` varchar(20) DEFAULT NULL,
  `aliencountry` varchar(50) DEFAULT NULL,
  `alienzip` varchar(20) DEFAULT NULL,
  `aliencitizenshipcountry` varchar(50) DEFAULT NULL,
  `aliencountryofbirth` varchar(50) DEFAULT NULL,
  `alienclassofadmission` varchar(30) DEFAULT NULL,
  `alieneducation` varchar(50) DEFAULT NULL,
  `alienmajor` varchar(50) DEFAULT NULL,
  `alieneducompletedyr` int(4) DEFAULT NULL,
  `aliencollege` varchar(100) DEFAULT NULL,
  `alienuniversityadd1` varchar(40) DEFAULT NULL,
  `alienuniversityadd2` varchar(30) DEFAULT NULL,
  `alienuniversitycity` varchar(30) DEFAULT NULL,
  `alienuniversitystate` varchar(30) DEFAULT NULL,
  `alienuniversitycountry` varchar(50) DEFAULT NULL,
  `alienuniversityzip` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `icertdataIND2` (`prevailingwage`,`OfferedWageFrom`),
  KEY `ind2` (`employer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
